bts: Fix BTS stubs
Using pre-processor macros for stubbing the functions
can cause compilation errors:

error: expected expression
bwindex = bts_get_bwindex("bo");
^
bts.h:37:28: note: expanded from macro 'bts_get_bwindex'

Signed-off-by: Vinay Kalia <vinaykalia@google.com>
Change-Id: Ib95cc5a90019e8acabf52c98f200c41f89d614b6
(cherry picked from commit df5345ed1ad50d9ccfbf7132330c663d5bd430a6)
Signed-off-by: Will McVicker <willmcvicker@google.com>