scsi: ufs: rename sdev_ufs_device into ufs_device_wlun
Propagate equivalent changes to upstream commit e2106584d011 ("scsi:
ufs: Rename sdev_ufs_device into ufs_device_wlun"). Fixes some build
issues such as the following:

drivers/scsi/ufs/ufs-pixel.c:749:49: error: no member named 'sdev_ufs_device' in 'struct ufs_hba'
        return snprintf(buf, PAGE_SIZE, "%.8s\n", hba->sdev_ufs_device->vendor);
                                                  ~~~  ^

Bug: 236216026
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I383926e3e9be9215af399d4f84d4632731b36b2f