usb: typec: tcpci_max77759: fix printf format
drivers/usb/typec/tcpm/google/tcpci_max77759.c:1130:8: error: format specifies type 'char *' but the argument has type 'unsigned int' [-Werror,-Wformat]
 1129 |                         LOG(LOG_LVL_DEBUG, chip->log, "%s: unable to set max voltage to %d, ret=%d",
      |                                                        ~~
      |                                                        %u
 1130 |                             chip->vbus_mv, ret, __func__);
      |                             ^~~~~~~~~~~~~

drivers/usb/typec/tcpm/google/tcpci_max77759.c:1655:17: error: format specifies type 'int' but the argument has type 'char *' [-Werror,-Wformat]
 1654 |                 LOG(LOG_LVL_DEBUG, chip->log, "%s turning off connected, ret=%d",
      |                                                                              ~~
      |                                                                              %s
 1655 |                     __func__, ret < 0 ? "Failed" : "Succeeded", ret);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:1655:51: error: data argument not used by format string [-Werror,-Wformat-extra-args]
 1654 |                 LOG(LOG_LVL_DEBUG, chip->log, "%s turning off connected, ret=%d",
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1655 |                     __func__, ret < 0 ? "Failed" : "Succeeded", ret);
      |                                                                 ^

Fixes: 2bef0379ca45 ("tcpci_max77759: Detect missing rp partners")
Fixes: 4bf0dbb42fff ("tcpci_max77759: Cleanup of debug log statements")
Fixes: 4031197b8312 ("usb: typec: tcpci_max77759: Add interface for checking connected status")
Test: TH
Bug: 348164658
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from https://partner-android-review.googlesource.com/q/commit:2e70e50ea01118fe8465a9442a372698179d41b1)
Merged-In: Iee6a38a7389592c5cfd04a8eee87105e6559a562
Change-Id: Iee6a38a7389592c5cfd04a8eee87105e6559a562