scsi: ufs: exynos: add missing cpu header include
After upstream refactored header files we now need to explicitly include
the cpu header file. Fixes the following build issue:

  drivers/scsi/ufs/ufs-exynos-dbg.c:881:14:
  error: implicit declaration of function 'cpu_clock' [-Werror,-Wimplicit-function-declaration]
        mgr->time = cpu_clock(raw_smp_processor_id());
                    ^
Bug: 215712060
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I85832e2328a30e839f327cfce719204b698365ab