eh: replace ffs() -> __ffs() and fls() -> __fls()
Switch to 64-bit variants to fix:

eh.c:1381:24: error: cast to smaller integer type 'int' from 'void *'
[-Werror,-Wvoid-pointer-to-int-cast]

alignment = 1 << (ffs((int)compr_data) - 1);

NOTE:
__ffs(value) == ffs(value) - 1

__ffs() returns a value one less than ffs(), so the code is adjusted accordingly.

Bug: 175723647
Test: echo 100000 > /sys/kernel/eh_test/test_compr_decompr
Signed-off-by: Petri Gynther <pgynther@google.com>
Change-Id: Iaae92bfcf6587b9dbb528fa982cb6a654a0636c5