soc: google: dss: fix -Wformat
Fixes the following error observed upgrading the toolchain:

drivers/soc/google/debug/debug-snapshot-utils.c:296:41: error: format
specifies type 'long' but the argument has type 'unsigned int'
[-Werror,-Wformat]
tsk->se.exec_start, state_array[idx], (tsk->__state),
                                      ^~~~~~~~~~~~~~
Bug: 261223935
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I8e84122b203da4148a6a77f4f1539fc8217c5d0f
(cherry picked from commit f7763928f85f203d0cd58aa603adac740518ebe0)