scsi: ufs: fix missing scsi_cmd.h header
Upstream commit 3f06f7800b80 ("scsi: ufs: Minimize #include directives")
cleaned up the scsi headers and now we need to explicitly add scsi_cmd.h
header to fix the following type of build errors:

drivers/scsi/ufs/ufs-exynos.c:1458:34: error: initializer element is not a compile-time constant
  static u64 exynos_ufs_dma_mask = DMA_BIT_MASK(32);
                                   ^~~~~~~~~~~~~~~~

drivers/scsi/ufs/ufs-pixel.c:87:27: error: incomplete definition of type 'struct scsi_cmnd'
                  opcode = (u8)(*lrbp->cmd->cmnd);
                                 ~~~~~~~~~^

Bug: 236216026
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I5989e9645f73db7e4e6b6c740fc085e3993d657d