scsi: ufs: fix implicit declaration in ufs-pixel.c
Upstream commit 4bc26113c603 ("scsi: ufs: Split the ufshcd.h header
file") moved the definitions used only by the UFS core into a private
header named 'ufshcd-priv.h'. Unfortunately the ufs-pixel driver uses
ufshcd_wb_get_query_index() which was relocated to this header.

While we consider whether using such function here is appropiate, let's
include the private header and fix the following build issue:

drivers/scsi/ufs/ufs-pixel.c:866:14: \
  error: implicit declaration of function 'ufshcd_wb_get_query_index' \
  is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                u8 index = ufshcd_wb_get_query_index(hba);
                           ^

Bug: 236216026
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: Ie0ea5ae046c60a34ad3dc9f06c0c57fa601c605e