usb: typec: tcpci_fusb307: fix missing type specifier
drivers/usb/typec/tcpm/tcpci_fusb307.c:212:8: error: type specifier missing,
defaults to 'int' [-Werror,-Wimplicit-int]
static enable_load_switch(struct fusb307b_plat *chip)
~~~~~~ ^
1 error generated.

Bug: 228686072
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Iddf0d68344f3001855ed6132a4da26cf124289fc