usb: typec: tcpci_fusb307b: fix printf format
drivers/usb/typec/tcpm/google/tcpci_fusb307.c:376:89: error: more '%' conversions than data arguments [-Werror,-Wformat-insufficient-args]
  376 |                       "%s pd_capable:%u pd_data_capable:%u no_bc_12:%u bc12_data_capable:%u attached:%u",
      |                                                                                                      ~^

Fixes: d4dfe0cf102d ("usb: typec: tcpci_fusb307b: Migrate to set_partner_usb_comm_capable")
Test: TH
Bug: 348164658
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from https://partner-android-review.googlesource.com/q/commit:31d54700a65817d4da420e6abdeb64671a260721)
Merged-In: Ib551e09169a2f050f204eb4740b2b1d462f92c80
Change-Id: Ib551e09169a2f050f204eb4740b2b1d462f92c80