eh: fix -Wformat
Fixes the following error observed during a toolchain upgrade:
drivers/soc/google/eh/eh_main.c:992:34: error: format specifies type
'unsigned long' but the argument has type 's64' (aka 'long long')
[-Werror,-Wformat]
return sysfs_emit(buf, "%lu\n", atomic64_read(&eh_dev->nr_stall));
                        ~~~     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        %lld

See also:
commit 8c24e8d2f656 ("eh: fix sysfs_emit formatting for atomic64_t")

Bug: 261223935
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: Ibaa9a622cea2aae2518cfdd3277057c7b88966b5