usb: typec: tcpci_max77759: fix more printf formats
drivers/usb/typec/tcpm/google/tcpci_max77759.c:846:8: error: format specifies type 'int' but the argument has type 'unsigned long' [-Werror,-Wformat]
                            (payload[1] & DP_STATUS_IRQ_HPD), chip->irq_hpd_count);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/typec/tcpm/google/tcpci_max77759.c:1410:6: error: format specifies type 'unsigned int' but the argument has type 'unsigned long' [-Werror,-Wformat]
            pwr_status & TCPC_POWER_STATUS_SRC_HI_VOLT, vbus_mv);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Note that the update here uses double negation which changes the output
of the messages for %d from <0 or large number> to a boolean <0 or 1>,
which I think is easier to read.

Fixes: 169b5f7363c7 ("tcpci_max77759: Signal irq_hpd")
Fixes: 43045e878a85 ("tcpci_max77759: clear EXTBST_CTRL when over voltage is detected")
Test: TH
Bug: 348164658
Change-Id: I5db8f40ab52b8a0475d43c9e312cf1cd633f9efb
Signed-off-by: André Draszik <draszik@google.com>