soc: google: hardlockup-debug: fix format specifier for __state
Clang 16.0.1 generates a new warning:

google-modules/soc/gs/drivers/soc/google/hardlockup-debug.c:298:6:
  error: format specifies type 'long' but the argument has type
  'unsigned int' [-Werror,-Wformat]

As warnings are errors, this breaks the build. Indeed, __state is
'unsigned int', not 'long', so update the format specifier.

Bug: 261223935
Fixes: 1ccb760daab5 ("soc: google: hardlockup-debug: update references to task->state")
Change-Id: I2006885d19c32990ee9fa4c28645e764d2996086
Signed-off-by: Alistair Delva <adelva@google.com>